[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# 编译时跳过warn部分
ignored_error_codes = [1878,5574,2018,2072,5667,9302,5815,3628,2519,8760,6321,5740,3420]

# rpc-url
rpc_endpoints = { mainnet = "https://rpc.ankr.com/eth", optimism = "https://opt-mainnet.g.alchemy.com/v2/demo", fantom = "https://rpc.ankr.com/fantom", arbitrum = "https://rpc.ankr.com/arbitrum", bsc = "https://rpc.ankr.com/bsc", moonriver = "https://moonriver.public.blastapi.io", gnosis = "https://rpc.ankr.com/gnosis", Avalanche = "https://rpc.ankr.com/avalanche", polygon = "https://rpc.ankr.com/polygon", celo = "https://rpc.ankr.com/celo" }


# See more config options https://github.com/foundry-rs/foundry/tree/master/config